### ISSUE TITLE
Where is the documentation ?

### ISSUE THREAD

**Issue by pauljouet** [RussAbbott/pylog#3]
Hello,

I would like to use pylog in a NLP research project. However I am struggling to find the documentation for the modules...  Is anywhere explicitly explained how to use them ? Is pylog only meant to create logic variables within Python or is it also possible to ask SWI Prolog queries ? If so how is it done ? It would help me not having to look in depth into the implementation.

Thanks

**Comment by RussAbbott** [comment]
Sorry. There is no formal documentation. I've just uploaded a paper that was submitted to The Programming Journal -- but rejected. It's in the PylogJournal directory. It's the most complete description of the system.  A much shorter version of the paper is in the WI-2020 directory. It's labeled IMCIC-21.pdf. I've also attached them below.


[IMCIC_21.pdf](https://github.com/RussAbbott/pylog/files/5558120/IMCIC_21.pdf)
[PyLog-Programming-Journal-08-03-20b.pdf](https://github.com/RussAbbott/pylog/files/5558123/PyLog-Programming-Journal-08-03-20b.pdf)
